### ISSUE TITLE
Make schema validation error of custom config file more user friendly 

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-core#15]
### Expected behavior

If the provided custom configuration file does not pass schema validation an understandable error message is shown. Ideally this would be followed by a pointer to what's wrong (invalid keyword and/or line number).

### Actual behavior

A stack trace is shown without any context or reference to the custom configuration file:
```
Error: Schema validation error
    at new SchemaValidationError (/home/lisk/lisk-2.0.0-alpha.0-ae0634b-Linux-x86_64/node_modules/lisk-framework/src/errors.js:39:3)
    at parseEnvArgAndValidate (/home/lisk/lisk-2.0.0-alpha.0-ae0634b-Linux-x86_64/node_modules/lisk-framework/src/controller/validator/index.js:106:10)
    at Configurator.getConfig (/home/lisk/lisk-2.0.0-alpha.0-ae0634b-Linux-x86_64/node_modules/lisk-framework/src/controller/configurator/configurator.js:76:10)
    at Object.<anonymous> (/home/lisk/lisk-2.0.0-alpha.0-ae0634b-Linux-x86_64/dist/helpers/config.js:48:46)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/lisk/lisk-2.0.0-alpha.0-ae0634b-Linux-x86_64/scripts/generate_config.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

### Steps to reproduce

Create custom `config.json` with e.g. misspelled key.

### Which version(s) does this affect? (Environment, OS, etc...)

`2.0`

**Comment by shuse2** [comment]
as of core 3.0, this issue no longer exist
