### ISSUE TITLE
Can not update to 3.0.0-beta5 with npm

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-core#478]
### Expected behavior

I want to update to 3.0.0-beta5 using npm.

### Actual behavior

I can not update to 3.0.0-beta5 with npm.
I can running core 3.0.0-beta5 with binary.
So,this issue seems to npm install only.

### Steps to reproduce

Using this document.

https://lisk.io/documentation/lisk-core/v3/setup/npm.html

```
hogehoge@lisk:~$ npm install --global --production lisk-core
npm ERR! code 1
npm ERR! path /home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/sodium-native
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/sodium-native/build'
npm ERR!   CC(target) Release/obj.target/sodium/binding.o
npm ERR! make: Leaving directory '/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/sodium-native/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.20.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/sodium-native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/hogehoge.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/hogehoge/.cache/node-gyp/12.20.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/hogehoge/.cache/node-gyp/12.20.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/hogehoge/.cache/node-gyp/12.20.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/sodium-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../binding.c:5:
npm ERR! ../libsodium/src/libsodium/include/sodium.h:5:10: fatal error: sodium/version.h: No such file or directory
npm ERR!     5 | #include "sodium/version.h"
npm ERR!       |          ^~~~~~~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [sodium.target.mk:117: Release/obj.target/sodium/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.4.0-70-generic
npm ERR! gyp ERR! command "/home/hogehoge/.nvm/versions/node/v12.20.1/bin/node" "/home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/hogehoge/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/sodium-native
npm ERR! gyp ERR! node -v v12.20.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hogehoge/.npm/_logs/2021-04-03T14_57_11_906Z-debug.log
hogehoge@lisk:~$ 

```

```
hogehoge@lisk:~$ sudo npm install --global --production lisk-core
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/lisk-core/node_modules/sodium-native
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/usr/lib/node_modules/lisk-core/node_modules/sodium-native/build'
npm ERR!   CC(target) Release/obj.target/sodium/binding.o
npm ERR! make: Leaving directory '/usr/lib/node_modules/lisk-core/node_modules/sodium-native/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.22.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/lisk-core/node_modules/sodium-native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/12.22.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.22.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.22.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/lisk-core/node_modules/sodium-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../binding.c:5:
npm ERR! ../libsodium/src/libsodium/include/sodium.h:5:10: fatal error: sodium/version.h: No such file or directory
npm ERR!     5 | #include "sodium/version.h"
npm ERR!       |          ^~~~~~~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [sodium.target.mk:117: Release/obj.target/sodium/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.4.0-70-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/lisk-core/node_modules/sodium-native
npm ERR! gyp ERR! node -v v12.22.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-03T15_08_22_171Z-debug.log
hogehoge@lisk:~$ 

```

### Which version(s) does this affect? (Environment, OS, etc...)

ubuntu 20.04.2 LTS
nvm v12.20.1 
npm v7.8.0

<img width="583" alt="スクリーンショット 2021-04-04 10 06 26" src="https://user-images.githubusercontent.com/14948578/113495598-ef8d1680-952d-11eb-9f6e-fe8000c37e92.png">

**Comment by lisknonanika** [comment]
I think I needed python2 to build.

Try the following:
`apt install -y python2-minimal`

**Comment by hitobb** [comment]
Thank you for your advice.
Unfortunately, installing python2 didn't fix it.

```
hogehoge@lisk:~$ python2
Python 2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
hogehoge@lisk:~$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
hogehoge@lisk:~$ 

```

BTW

From ubuntu 20.04, python2 is an additional installation. 
Therefore, npm installer should be compatible with python3.

**Comment by hitobb** [comment]
This issue is only related to the 3.0.0 beta, so close  this.
