### ISSUE TITLE
Source setup fails on fresh machine

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-core#61]
### Expected behavior

By following the documentation for Lisk Core, it should be possible to install Lisk Core successfully without any errors.

### Actual behavior

When following the documentation on a fresh Ubuntu 18.04 machine the setup process fails when installing the dependencies:

```bash
lisk@mona-betanet:~/lisk-core$ npm ci --registry https://npm.lisk.io
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.9 install /home/lisk/lisk-core/node_modules/fsevents
> node install


> sodium-native@2.2.1 install /home/lisk/lisk-core/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> jsonpath@1.0.1 postinstall /home/lisk/lisk-core/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


> sodium-native@2.2.4 install /home/lisk/lisk-core/node_modules/lisk-framework/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> @newrelic/native-metrics@3.1.2 install /home/lisk/lisk-core/node_modules/@newrelic/native-metrics
> node ./lib/pre-build.js install native_metrics

> /home/lisk/.nvm/versions/node/v10.15.3/bin/node /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/lisk/.nvm/versions/node/v10.15.3/bin/node" "/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean" "configure"
gyp ERR! cwd /home/lisk/lisk-core/node_modules/@newrelic/native-metrics
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
install successful: _newrelic_native_metrics-3_1_2-native_metrics-64-linux-x64

> dtrace-provider@0.8.7 install /home/lisk/lisk-core/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/lisk/.nvm/versions/node/v10.15.3/bin/node" "/home/lisk/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lisk/lisk-core/node_modules/dtrace-provider
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> sc-uws@10.148.2 install /home/lisk/lisk-core/node_modules/sc-uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> fsevents@1.2.9 install /home/lisk/lisk-core/node_modules/lisk-commander/node_modules/fsevents
> node install


> sodium-native@2.2.1 install /home/lisk/lisk-core/node_modules/lisk-commander/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

added 1250 packages in 20.059s
```

### Steps to reproduce

Try to install Lisk Core v2.0.0 by following steps described in https://github.com/LiskHQ/lisk-docs/blob/dev-core-2.0.0/setup/source.md

### Which version(s) does this affect? (Environment, OS, etc...)
v2.0.0-alpha.5

**Comment by fchavant** [comment]
@Tschakki you're missing `python` (version 2, likely)

**Comment by Tschakki** [comment]
@fchavant hmm, seems on newer Ubuntu versions, there is only version 3 installed by default...

I tried to install version 2 as well:
```
apt-get install python2.7
```

An tried to run 
```
npm ci --registry https://npm.lisk.io
```

again, but with the same error as result.

Here they recommend to not remove python 3: https://askubuntu.com/questions/1104397/python2-7-not-working-in-18-04-python3-is-installed

**Comment by Tschakki** [comment]
Got it fixed by installing `python-minimal`:

```bash
sudo apt install python-minimal
```

**Comment by 4miners** [comment]
Fixed in https://github.com/LiskHQ/lisk-docs/commit/35d0b7d6c9ff0f0a4f0b8f680f111e45c5dfcaee
