### ISSUE TITLE
Lisk Core stops working on different servers: Creating a duplicate QueryFile object for the same file

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-core#71]
A week ago Lisk Core on Server 1 (Ubuntu 16.04.3 LTS) stopped. Some days later Lisk Core on Server 2 (Ubuntu 16.04.5 LTS) stopped and a day later Lisk Core on Server 3 (Ubuntu 16.04.4 LTS).

- This happened already in April on all three servers at different days.
- All servers are hosted by different providers.
- All servers are running Lisk Core 1.6.0

 So, I checked `~/lisk-main/logs/mainnet/lisk.app.err` and on all three nodes it shows **exactly** the same before Core stopped working. I had to restart Core to get it working again. Server 1, restarted one week ago, is still running. 

**Here's the err-log:**

```
2019-05-31 07:19:57 115: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 115:     /home/username/lisk-main/framework/src/components/storage/sql/accounts/get.sql
2019-05-31 07:19:57 115:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 115:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 115:     at Account.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 115:     at new Account (/home/username/lisk-main/framework/src/components/storage/entities/account.js:281:20)
2019-05-31 07:19:57 115:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 115:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:37:10)
2019-05-31 07:19:57 115:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 115:
2019-05-31 07:19:57 116: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 116:     /home/username/lisk-main/framework/src/components/storage/sql/accounts/get_extended.sql
2019-05-31 07:19:57 116:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 116:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 116:     at Account.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 116:     at new Account (/home/username/lisk-main/framework/src/components/storage/entities/account.js:281:20)
2019-05-31 07:19:57 116:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 116:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:37:10)
2019-05-31 07:19:57 116:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 116:
2019-05-31 07:19:57 116: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 116:     /home/username/lisk-main/framework/src/components/storage/sql/accounts/count.sql
2019-05-31 07:19:57 116:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 116:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 116:     at Account.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 116:     at new Account (/home/username/lisk-main/framework/src/components/storage/entities/account.js:281:20)
2019-05-31 07:19:57 116:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 116:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:37:10)
2019-05-31 07:19:57 116:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 116:
2019-05-31 07:19:57 116: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 117:     /home/username/lisk-main/framework/src/components/storage/sql/accounts/is_persisted.sql
2019-05-31 07:19:57 117:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 117:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 117:     at Account.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 117:     at new Account (/home/username/lisk-main/framework/src/components/storage/entities/account.js:281:20)
2019-05-31 07:19:57 117:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 117:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:37:10)
2019-05-31 07:19:57 117:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 117:
2019-05-31 07:19:57 117: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 117:     /home/username/lisk-main/framework/src/components/storage/sql/transactions/get.sql
2019-05-31 07:19:57 117:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 117:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 117:     at Transaction.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 117:     at new Transaction (/home/username/lisk-main/framework/src/components/storage/entities/transaction.js:245:20)
2019-05-31 07:19:57 117:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:165:28)
2019-05-31 07:19:57 117:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 117:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 117:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 117:
2019-05-31 07:19:57 118: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 118:     /home/username/lisk-main/framework/src/components/storage/sql/transactions/get_extended.sql
2019-05-31 07:19:57 118:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 118:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 118:     at Transaction.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 118:     at new Transaction (/home/username/lisk-main/framework/src/components/storage/entities/transaction.js:245:20)
2019-05-31 07:19:57 118:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:165:28)
2019-05-31 07:19:57 118:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 118:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 118:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 118:
2019-05-31 07:19:57 118: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 118:     /home/username/lisk-main/framework/src/components/storage/sql/transactions/is_persisted.sql
2019-05-31 07:19:57 118:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 118:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 118:     at Transaction.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 118:     at new Transaction (/home/username/lisk-main/framework/src/components/storage/entities/transaction.js:245:20)
2019-05-31 07:19:57 118:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:165:28)
2019-05-31 07:19:57 118:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 118:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 118:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 118:
2019-05-31 07:19:57 118: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 118:     /home/username/lisk-main/framework/src/components/storage/sql/transactions/count.sql
2019-05-31 07:19:57 118:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 118:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 118:     at Transaction.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 118:     at new Transaction (/home/username/lisk-main/framework/src/components/storage/entities/transaction.js:245:20)
2019-05-31 07:19:57 118:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:165:28)
2019-05-31 07:19:57 118:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 118:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 118:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 119:
2019-05-31 07:19:57 119: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 119:     /home/username/lisk-main/framework/src/components/storage/sql/transactions/count_all.sql
2019-05-31 07:19:57 119:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 119:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 119:     at Transaction.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 119:     at new Transaction (/home/username/lisk-main/framework/src/components/storage/entities/transaction.js:245:20)
2019-05-31 07:19:57 119:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:165:28)
2019-05-31 07:19:57 119:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 119:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 119:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 119:
2019-05-31 07:19:57 119: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 119:     /home/username/lisk-main/framework/src/components/storage/sql/blocks/get.sql
2019-05-31 07:19:57 119:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 119:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 119:     at Block.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 119:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:208:20)
2019-05-31 07:19:57 119:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 119:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 119:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 119:
2019-05-31 07:19:57 120: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 120:     /home/username/lisk-main/framework/src/components/storage/sql/blocks/count.sql
2019-05-31 07:19:57 120:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 120:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 120:     at Block.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 120:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:208:20)
2019-05-31 07:19:57 120:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 120:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 120:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 120:
2019-05-31 07:19:57 121: WARNING: Creating a duplicate QueryFile object for the same file -
2019-05-31 07:19:57 121:     /home/username/lisk-main/framework/src/components/storage/sql/blocks/is_persisted.sql
2019-05-31 07:19:57 121:     at PgpAdapter.loadSQLFile (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:173:14)
2019-05-31 07:19:57 121:     at Object.keys.forEach.key (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:221:56)
2019-05-31 07:19:57 121:     at Block.loadSQLFiles (/home/username/lisk-main/framework/src/components/storage/entities/base_entity.js:219:25)
2019-05-31 07:19:57 121:     at new Block (/home/username/lisk-main/framework/src/components/storage/entities/block.js:208:20)
2019-05-31 07:19:57 121:     at Storage.registerEntity (/home/username/lisk-main/framework/src/components/storage/storage.js:86:24)
2019-05-31 07:19:57 121:     at createStorageComponent (/home/username/lisk-main/framework/src/components/storage/index.js:38:10)
2019-05-31 07:19:57 121:     at Chain.bootstrap (/home/username/lisk-main/framework/src/modules/chain/chain.js:123:20)
2019-05-31 07:19:57 121:
2019-05-31 07:19:57 133: WARNING: Creating a duplicate database object for the same connection.
2019-05-31 07:19:57 133:     at PgpAdapter.connect (/home/username/lisk-main/framework/src/components/storage/adapters/pgp_adapter.js:95:18)
2019-05-31 07:19:57 133:     at Storage.bootstrap (/home/username/lisk-main/framework/src/components/storage/storage.js:43:23)
2019-05-31 07:19:57 133:     at module.exports (/home/username/lisk-main/framework/src/modules/http_api/init_steps/bootstrap_storage.js:19:32)
2019-05-31 07:19:57 133:     at HttpApi.bootstrap (/home/username/lisk-main/framework/src/modules/http_api/http_api.js:76:9)
2019-05-31 07:19:57 133:
2019-05-31 07:19:57 180: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
2019-05-31 07:19:57 180: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
2019-05-31 07:19:57 180: WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
2019-05-31 07:19:57 180: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
2019-05-31 07:19:57 376: [{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/ReducedBlock","path":["definitions","ReducedBlock"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/CommonBlock","path":["definitions","CommonBlock"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/PeersList","path":["definitions","PeersList"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/parameters/data","path":["parameters","data"]}] 2
```

**Comment by nazarhussain** [comment]
@punkr0ck Hi, I checked the logs above, I certainly believe it does not related to the server crash. As these are few warning messages, which can appear on normal startup as well. 

Do you know exact time when server crashes, so we can locate activities of that time in the logs. 

Also please compress and share the folder `~/lisk-main/logs/mainnet/` so we can look into further details.

**Comment by punkr0ck** [comment]
It's too late. The logs get erased every week. If it happens again, I will share everything.

**Comment by ManuGowda** [comment]
Closing this issue as it's no longer occurs, and it was not reported back after long time.
