### ISSUE TITLE
Failed to generate blocks in v4.0.0-beta.1

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-core#789]
In `v4.0.0-beta.1` the noded stopped to generate blocks with the following error. The chain on the node kept moving but stopped to generate blocks.

Error:
```
2023-06-08T02:09:33.225Z ERROR betanet engine 332042 [err=Execution context is already initialized with 6e0dd8df5d840a67ff8bfc7f291e8de2bf65ad1f86399a4d05ac7c8e9c41e643] Failed to generate a block
/home/lisk/lisk-core/bin/lisk-core: line 54: 332042 Killed                  "$NODE" "$DIR/run" "$@"
```

**Comment by sameersubudhi** [comment]
@punkrock What is the environment (OS) you're running the node in?

**Comment by sameersubudhi** [comment]
Did you happen to run the same generator (w/ same keys) on another node simultaneously?

**Comment by punkrock** [comment]
@sameersubudhi No, this is my only node and I did nothing. The error just showed up and my node stopped generating blocks but the chain kept moving like nothing happened.

**Comment by punkrock** [comment]
Today it happened again. Here the full logs:

```
2023-06-09T01:37:27.287Z WARN betanet engine 505075 [error=Apply penalty and restart synchronization mechanism with reason: Peer didn't return any block after requesting blocks reason=Peer didn't return any block after requesting blocks] Applying penalty and restarting synchronization
2023-06-09T01:37:35.249Z ERROR betanet engine 505075 [peerId=216.238.66.142:7667 err=List of connected peers is empty] Fail to handle received block
2023-06-09T01:42:59.780Z ERROR betanet engine 505075 [err=Error: Contradicting headers for the block with id: 96d20e790af93ac6f4d98bfe8b25690ac76413ffbc21a2a3c1b10cca4144f42c] Fail to execute block.
2023-06-09T01:44:11.624Z ERROR betanet engine 505075 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T01:45:26.249Z WARN betanet engine 505075 [error=Apply penalty and restart synchronization mechanism with reason: Peer didn't return any block after requesting blocks reason=Peer didn't return any block after requesting blocks] Applying penalty and restarting synchronization
2023-06-09T01:45:31.537Z ERROR betanet engine 505075 [peerId=45.32.203.143:7667 err=List of connected peers is empty] Fail to handle received block
2023-06-09T01:47:41.376Z ERROR betanet engine 505075 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T01:47:54.078Z ERROR betanet engine 505075 [peerId=45.32.203.143:7667 err=Event response for 'rpc-request' timed out] Fail to handle received block
2023-06-09T01:48:06.801Z ERROR betanet engine 505075 [peerId=45.32.203.143:7667 err=Event response for 'rpc-request' timed out] Fail to handle received block
2023-06-09T01:48:38.674Z ERROR betanet engine 505075 [peerId=45.32.203.143:7667 err=Event response for 'rpc-request' timed out] Fail to handle received block
/home/lisk/lisk-core/bin/lisk-core: line 54: 505075 Killed                  "$NODE" "$DIR/run" "$@"
2023-06-09T08:45:52.162Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T10:40:36.531Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T10:40:36.751Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T10:40:36.892Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T10:40:37.056Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T10:52:57.382Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-09T10:55:08.846Z ERROR betanet engine 516984 [peerId=20.48.103.139:7667 err=Event response for 'rpc-request' timed out] Fail to handle received block
2023-06-09T11:20:33.118Z ERROR betanet engine 516984 [err=Event response for 'rpc-request' timed out] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
/home/lisk/lisk-core/bin/lisk-core: line 54: 516984 Killed                  "$NODE" "$DIR/run" "$@"
```

**Comment by sameersubudhi** [comment]
@punkrock Could you please run the node with `trace` logs and share them when this happens again?

**Comment by ManuGowda** [comment]
Moving this issue to SDK for further resolution.

**Comment by punkrock** [comment]
@sameersubudhi 

I am failing to generate blocks again. Here the error logs (trace):

```
2023-06-12T03:42:11.199Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:11.355Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:11.535Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:12.090Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:12.815Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:12.822Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:12.822Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:12.822Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:12.823Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:42:30.781Z ERROR betanet engine 573312 [peerId=45.32.203.143:7667 err=Apply penalty and abort synchronization mechanism with reason: Peer didn't return a common block trace=ApplyPenaltyAndAbortError: Apply penalty and abort synchronization mechanism with reason: Peer didn't return a common block
    at new SynchronizerError (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/errors.js:5:1)
    at new ApplyPenaltyAndAbortError (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/errors.js:35:9)
    at FastChainSwitchingMechanism._queryBlocks (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/fast_chain_switching_mechanism.js:61:19)
    at FastChainSwitchingMechanism.run (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/fast_chain_switching_mechanism.js:15:35)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
    at async /home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/synchronizer.js:47:13
    at async Mutex.runExclusive (/home/lisk/lisk-core/node_modules/@liskhq/lisk-utils/dist-node/job_handlers/mutex.js:23:20)
    at async Synchronizer.run (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/synchronizer.js:33:9)] Fail to handle received block
2023-06-12T03:43:18.448Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:43:18.771Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:43:19.134Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:43:19.258Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:43:19.377Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:43:19.426Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T03:43:19.606Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T08:34:22.246Z ERROR betanet engine 573312 [peerId=80.211.194.139:7667 err=List of connected peers is empty trace=Error: List of connected peers is empty
    at BlockSynchronizationMechanism._computeBestPeer (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/block_synchronization_mechanism.js:231:19)
    at BlockSynchronizationMechanism.run (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/block_synchronization_mechanism.js:28:31)
    at /home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/synchronizer.js:47:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Mutex.runExclusive (/home/lisk/lisk-core/node_modules/@liskhq/lisk-utils/dist-node/job_handlers/mutex.js:23:20)
    at async Synchronizer.run (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/synchronizer/synchronizer.js:33:9)
    at async Consensus._sync (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/consensus.js:584:13)
    at async /home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/consensus.js:310:17
    at async Mutex.runExclusive (/home/lisk/lisk-core/node_modules/@liskhq/lisk-utils/dist-node/job_handlers/mutex.js:23:20)] Fail to handle received block
2023-06-12T09:04:41.609Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
2023-06-12T09:07:41.608Z ERROR betanet engine 573312 [err=Event response for 'rpc-request' timed out trace=TimeoutError: Event response for 'rpc-request' timed out
    at SCClientSocket._handleEventAckTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:678:17)
    at Timeout._onTimeout (/home/lisk/lisk-core/node_modules/socketcluster-client/lib/scclientsocket.js:708:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)] EVENT_FAILED_TO_FETCH_PEER_INFO: Failed to fetch peer info
/home/lisk/lisk-core/bin/lisk-core: line 54: 573312 Killed                  "$NODE" "$DIR/run" "$@"
2023-06-12T13:31:50.548Z ERROR betanet engine 581650 [err=Incoming transaction fee is not sufficient to replace existing transaction trace=TransactionPoolError: Incoming transaction fee is not sufficient to replace existing transaction
    at TransactionPool.add (/home/lisk/lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/transaction_pool.js:127:24)
    at async NetworkEndpoint._receiveTransaction (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:162:27)
    at async NetworkEndpoint.handleEventPostTransactionsAnnouncement (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:132:21)] Failed to add transaction to pool.
2023-06-12T13:31:51.151Z ERROR betanet engine 581650 [err=Incoming transaction fee is not sufficient to replace existing transaction trace=TransactionPoolError: Incoming transaction fee is not sufficient to replace existing transaction
    at TransactionPool.add (/home/lisk/lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/transaction_pool.js:127:24)
    at async NetworkEndpoint._receiveTransaction (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:162:27)
    at async NetworkEndpoint.handleEventPostTransactionsAnnouncement (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:132:21)] Failed to add transaction to pool.
2023-06-12T13:34:23.619Z ERROR betanet engine 581650 [err=Incoming transaction fee is not sufficient to replace existing transaction trace=TransactionPoolError: Incoming transaction fee is not sufficient to replace existing transaction
    at TransactionPool.add (/home/lisk/lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/transaction_pool.js:127:24)
    at async NetworkEndpoint._receiveTransaction (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:162:27)
    at async NetworkEndpoint.handleEventPostTransactionsAnnouncement (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:132:21)] Failed to add transaction to pool.
2023-06-12T13:35:38.604Z ERROR betanet engine 581650 [err=Incoming transaction fee is not sufficient to replace existing transaction trace=TransactionPoolError: Incoming transaction fee is not sufficient to replace existing transaction
    at TransactionPool.add (/home/lisk/lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/transaction_pool.js:127:24)
    at async NetworkEndpoint._receiveTransaction (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:162:27)
    at async NetworkEndpoint.handleEventPostTransactionsAnnouncement (/home/lisk/lisk-core/node_modules/lisk-framework/dist-node/engine/generator/network_endpoint.js:132:21)] Failed to add transaction to pool.
/home/lisk/lisk-core/bin/lisk-core: line 54: 581650 Killed                  "$NODE" "$DIR/run" "$@"
/home/lisk/lisk-core/bin/lisk-core: line 54: 586594 Killed                  "$NODE" "$DIR/run" "$@"
```
